# Generated by Django 5.2 on 2025-04-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskAssigned',
            new_name='TaskAssignedDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskCompleted',
            new_name='TaskCompleteDate',
        ),
    ]
